-- MCP.lua
require("Engine.Scripts.Core.Class")
require("Engine.Scripts.Core.Debug")
require("Engine.Scripts.Core.Application")
require("Engine.Scripts.Core.SceneManager")
require("Engine.Scripts.UI.Widget")
require("Engine.Scripts.UI.BarWidget")
require("Engine.Scripts.UI.ImageWidget")
require("Engine.Scripts.UI.TextWidget")
require("Engine.Scripts.UI.ButtonWidget")
require("Engine.Scripts.UI.SelectionWidget")
require("Engine.Scripts.UI.ToggleWidget")